export const UPDATE_PAGES = 'PAGES/UPDATE_PAGES';
export const UPDATE_LOADING = 'PAGES/UPDATE_LOADING';
export const FETCHED_PAGES = 'PAGES/FETCHED_PAGES';
export const SAVING_CHANGES = 'PAGES/SAVING_CHANGES';
